apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50